name: pincontrol
services:  
  pincontrol:
    container_name: pincontrol
    build:
     context: .
    #ports:
    # - 1883:1883 internal communication over network!
    networks:
     - mqtt_network	
    volumes:
     - /dev/gpiomem
    privileged: true
    restart: always
    secrets:
      - mqtt_pw

secrets:
  mqtt_pw:
    file: ~/sec/mqtt_pw

networks:
  mqtt_network:
    external: true
